### ISSUE TITLE
图片上传，请问如何监听啊，自己自定义如何编写

### ISSUE THREAD

**Issue by kong-qi** [capricorncd/zx-editor#16]
要自己全部从头开始写到尾巴？我就想直接把base64换成图片路径

**Comment by capricorncd** [comment]
```
// 自定义选择图片，点击底部工具栏图片图标是触发
zxEditor.on('select-picture', _ => {
  // hybrid模式开发时，此处可以调用原生App提供的接口，访问图片文件选择列表
  // 执行图片文件数据获取，
  // 或者获取由原生App处理并上传完成的图片url
  zxEditor.addImage('图片url地址或base64图片数据')
  // 其他操作...
})
```

**Comment by kong-qi** [comment]
这个只是总写，其实我就想把他上传到服务器，不想重写全部。如果写了上面的那个，就触发不了图片上传了。你这个获取不到base64图片数据源，我意思想获得base64源上传到服务器，然后替换这个base64.

**Comment by kong-qi** [comment]
如何我用了很猥琐的方法，直接修改源码，也实现了上传功能和替换图片地址，但这种不是好方法，我看你的文档没有说。有点尬尴

**Comment by capricorncd** [comment]
其实在zxEditor.on('select-picture', _ => {})这个里面写也多不了几行代码，主要就是去触发一个<input type="file">的click事件，然后监听其change事件

**Comment by kong-qi** [comment]
嗯，是的，等于自己自定义上传了，这个方法，其实我想说，最低的配置和重写方法，写个服务器替换图片函数回调，不过我看你都是压缩过的，修改起来有点困难，wenpack不是很熟悉，你的源码。如果可以你就加个base64图片替换回调，那样更加方便，不用再自己重写，虽然说代码不多，但是还是要写，比如图片压缩之类，如果内置了就不需要再写了。

**Comment by capricorncd** [comment]
```
# 安装依赖
npm i

# 运行开发模式
# 通过 `http://localhost:9001` 可以访问
npm run dev

# 生成项目文件
npm run build
```

**Comment by kong-qi** [comment]
嗯，是的，等于自己自定义上传了，这个方法，其实我想说，最低的配置和重写方法，写个服务器替换图片函数回调，不过我看你都是压缩过的，修改起来有点困难，wenpack不是很熟悉，你的源码。如果可以你就加个base64图片替换回调，那样更加方便，不用再自己重写，虽然说代码不多，但是还是要写，比如图片压缩之类，如果内置了就不需要再写了。

**Comment by kong-qi** [comment]
谢了，大佬。

**Comment by capricorncd** [comment]
```
zxEditor.setImageSrc(imgId, imgUrl)
将ID为imgId的图片base64地址，替换为新的imgUrl。需配合getBase64Images()方法使用。
@return boolean
```
这个方法能否解决你的问题？

**Comment by capricorncd** [comment]
图片先上传再添加至编辑器内demo请见：
https://github.com/capricorncd/zx-editor/tree/master/demo
```
./demo/upload.html
./demo/php/index.php
```
