### ISSUE TITLE
npm run build 为什么只有首次会生成

### ISSUE THREAD

**Issue by yuditxj** [capricorncd/zx-editor#26]
我执行npm run build
在dist文件夹中只有首次会生成zx-editor.css  zx-editor-min.css zx-editor.css

以后执行npm run build在dist文件只会生成zx-editor-min.js

这是为什么呢？

**Comment by capricorncd** [comment]
未压缩文件是用rollup生成的，所以webpack build不会出现css文件。
下一个版本优化...

**Comment by capricorncd** [comment]
v3.0.0
