### ISSUE TITLE
怎么去掉编辑器文字样式里面的颜色项，不需要颜色项，希望可以丰富配置，控制显示每一个配置项

### ISSUE THREAD

**Issue by caigongda** [capricorncd/zx-editor#37]
怎么去掉编辑器文字样式里面的颜色项，不需要颜色项，希望可以丰富配置，控制显示每一个配置项
文字样式那一排按钮希望也可以配置，大写的L C R很多人不知道什么意思

**Comment by caigongda** [comment]
非常不错的编辑器，找了很久发现这个最好用，我是用在APP上的，APP上的编辑器太少了，嵌入网页目前就这个编辑器最好了，宣传一波的话应该会更受欢迎，另外感觉好像有点卡顿。

**Comment by limnQQ** [comment]
> 非常不错的编辑器，找了很久发现这个最好用，我是用在APP上的，APP上的编辑器太少了，嵌入网页目前就这个编辑器最好了，宣传一波的话应该会更受欢迎，另外感觉好像有点卡顿。

您好，请问ios兼容吗

**Comment by capricorncd** [comment]
参数textStyleColors设为`[]`空数组即可。
```
{
  textStyleColors: []
}
```
