### ISSUE TITLE
使用3.0.2版本出现的问题

### ISSUE THREAD

**Issue by hjplk** [capricorncd/zx-editor#38]
我是在Vue单页面应用中当做子组件来使用的，通过import ZxEditor from 'zx-editor';来引入。
问题：
1.页面显示异常，编辑器的高度默认设置的很高，底部工具栏会始终显示
![image](https://user-images.githubusercontent.com/34955738/60765675-abf34780-a0d0-11e9-8f42-1722a030d0ab.png)
2.点击编辑框会默认选择图片
![image](https://user-images.githubusercontent.com/34955738/60765689-ce856080-a0d0-11e9-98ec-d578f56243c9.png)
请问大佬如何处理

**Comment by limnQQ** [comment]
> 我是在Vue单页面应用中当做子组件来使用的，通过import ZxEditor from 'zx-editor';来引入。
> 问题：
> 1.页面显示异常，编辑器的高度默认设置的很高，底部工具栏会始终显示
> ![image](https://user-images.githubusercontent.com/34955738/60765675-abf34780-a0d0-11e9-8f42-1722a030d0ab.png)
> 2.点击编辑框会默认选择图片
> ![image](https://user-images.githubusercontent.com/34955738/60765689-ce856080-a0d0-11e9-98ec-d578f56243c9.png)
> 请问大佬如何处理

请问在vue怎么引用ZxEditor

**Comment by heihei001** [comment]
你样式没有引入
