### ISSUE TITLE
为啥 github更新了3.0.4 npm没更新

### ISSUE THREAD

**Issue by leecn-web** [capricorncd/zx-editor#55]
github上 更新了 3.0.4  可以使用toolbar.addButton添加按钮，而3.0.2使用这种方式添加的时候 不能传入event属性，传入即报错

**Comment by capricorncd** [comment]
npm的密码忘了，不能publish。改天重置密码试一下

**Comment by leecn-web** [comment]
> npm的密码忘了，不能publish。改天重置密码试一下

好的，大佬
